# Site settings
title: The Grimoire
author: Saph, thebombzen
description:
  A searchable D&D 5e spell list, sorted by class and level.
baseurl: /lazydm699.github.io # the subpath of your site, e.g. /blog/
url: lazydm699.github.io # the base hostname & protocol for your site
source-url: https://github.com/LazyDM699/lazydm699.github.io/
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"
